name: Build Image & Push an Image to ECR (CI)

on:
  push:
    branches: [main]

env:
  AWS_REGION: "ap-northeast-2"

permissions:
  id-token: write
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-var.outputs.IMAGE_TAG }}
    steps:
      - name: Git-Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ARN_ECR_PUSH_ROLE }}
          role-session-name: Private-ECR-PushRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set variable
        id: set-variable
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=ejl-repo" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Docker build
        id: build-image
        run: |
          docker build \
            -f Dockerfile \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Docker Image Push
        id: image-push
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Checkout for Kustomize repository
        uses: actions/checkout@v2
        with:
          # kubernetes yaml 파일 저장
          repository: Leeeuijooo/Kustomize_test
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: Kustomize_test

      - name: Update k8s resource
        run: |
          pwd
          cd Kustomize_test/overlays/dev/
          echo \${{ steps.login-ecr.outputs.registry }}/\${{ env.ECR_REPOSITORY }}
          echo \${{ steps.login-ecr.outputs.registry }}/\${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          kustomize edit set image \${{ steps.login-ecr.outputs.registry }}/\${{ env.ECR_REPOSITORY }}=\${{ steps.login-ecr.outputs.registry }}/\${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          cat kustomization.yml

      - name: Commit Manifest files
        run: |
          cd Kustomize_test
          git config --global user.email "euijoo3233@gmail.com"
          git config --global user.name "euijoo"
          git add .
          git commit -m "Update Manifest file Image Tag $IMAGE_TAG"
          git remote set-url origin https://x-access-token:${GIT_AUTH_TOKEN}@github.com/Leeeuijooo/Kustomize_test.git
          git push -u origin main
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}





        








